adds course to breadcrumb if block is inside a course
learningworks/moodle-block_advnotifications pull request #31
Opened 2021-09-20 18:41 UTC by danielneis

Hi,
Hope you like this little improvement.
It helps admin keeps context of the course in case he/she is accessing the block inside a course.

I would also consider add the the corresponding course to each notification on the table. What do you think about it?

Also, I'm planning to make some other improvements to this plugin like the ability to send Moodle notifications (that will appear on the bell icon and will be sent optionally via email or push notifications to the app) on the start date of a notification.

Best,
Daniel

2021-09-20 18:58 UTC, jprovasnik commented
These are two WONDERFUL suggestions

2021-09-23 19:37 UTC, zpottie commented
Thanks @danielneis - makes sense! 😄  Just added a comment at one place. I don't have an instance of Moodle currently to check, so just wanted to make sure. 👍 
Thanks again!

2021-09-23 20:07 UTC, zpottie requested changes

2021-09-24 17:36 UTC, danielneis commented on pages/notifications.php
>  }
Hi!
I just made another commit to fix the case where user goes through site administration / blocks / advanced notifications / manage.
I didn't know it was different from the "dashboard" notifications where we can mark it as "global".

Best,
Daniel

2021-10-14 19:47 UTC, zpottie approved these changes

2021-10-14 19:48 UTC, merged

2021-10-14 19:49 UTC, zpottie commented
Thanks @danielneis - merged it in!